class Skill < ActiveHash::Base
  self.data = [
    # 言語
    { name: "Anaconda" },
    { name: "Bash/Shell/PowerShell" },
    { name: "C" },
    { name: "C#" },
    { name: "C++" },
    { name: "Clojure" },
    { name: "COBOL" },
    { name: "CoffeeScript" },
    { name: "Dart" },
    { name: "Elixir" },
    { name: "Erlang" },
    { name: "Go" },
    { name: "Groovy" },
    { name: "Haskell" },
    { name: "HTML/CSS" },
    { name: "Java" },
    { name: "JavaScript" },
    { name: "JSON" },
    { name: "Kotlin" },
    { name: "Node.js" },
    { name: "Objective-C" },
    { name: "Perl" },
    { name: "PHP" },
    { name: "Python" },
    { name: "R" },
    { name: "Ruby" },
    { name: "Rust" },
    { name: "Scala" },
    { name: "SQL" },
    { name: "Swift" },
    { name: "TypeScript" },
    { name: "VBA" },
    # フレームワーク
    { name: ".NET Framework" },
    { name: "AngularJS" },
    { name: "Apache Cordova" },
    { name: "Bootstrap" },
    { name: "CakePHP" },
    { name: "Cocos2d-x" } , 
    { name: "Django" },
    { name: "Electron" },
    { name: "Laravel" },
    { name: "Nuxt.js" },
    { name: "RSpec" },
    { name: "React" },
    { name: "React Native" },
    { name: "Redux" },
    { name: "Ruby on Rails" },
    { name: "Vue.js" },
    { name: "WPF" },
    { name: "Xamarin" },
    # データベース
    { name: "Microsoft SQL Server" },
    { name: "MongoDB" },
    { name: "MySQL" },
    { name: "Oracle Database" },
    { name: "PostgreSQL" },
    { name: "Redis" },
    # ライブラリ
    { name: "Chainer" },
    { name: "Keras" },
    { name: "OpenCV" },
    { name: "Pandas" },
    { name: "TensorFlow" },
    { name: "jQuery" },
    # ソフトウェア
    { name: "Android Studio" },
    { name: "Ansible" },
    { name: "Apache" },
    { name: "Bash" },
    { name: "Chef" },
    { name: "Docker" },
    { name: "Eclipse" },
    { name: "Elasticsearch" },
    { name: "Fluentd" },
    { name: "Git" },
    { name: "GitLab" },
    { name: "Gradle" },
    { name: "Jenkins" },
    { name: "Kubernetes" },
    { name: "Nginx" },
    { name: "Redmine" },
    { name: "Selenium" },
    { name: "Slack" },
    { name: "Unity" },
    { name: "Vagrant" },
    { name: "Vim" },
    { name: "VirtualBox" },
    { name: "WordPress" },
    { name: "Xcode" },
    # OS
    { name: "Android" },
    { name: "CentOS" },
    { name: "Debian" },
    { name: "iOS" },
    { name: "Linux" },
    { name: "Mac" },
    { name: "OSX" },
    { name: "Ubuntu" },
    { name: "Windows" },
    # サービス
    { name: "AWS" },
    { name: "Azure" },
    { name: "BigQuery" },
    { name: "EC2" },
    { name: "Firebase" },
    { name: "GAS" },
    { name: "GCP" },
    { name: "GitHub" },
    { name: "Google Analytics" },
    { name: "Heroku" },
    { name: "S3" },
    { name: "Salesforce" },
    # 技術
    { name: "AI(人工知能)" },
    { name: "API" },
    { name: "AR(拡張現実)" },
    { name: "CI(継続的インテグレーション)" },
    { name: "Deep Learning(深層学習)" },
    { name: "IoT" },
    { name: "TDD(テスト駆動開発)" },
    { name: "VR(仮想現実)" },
    { name: "スクレイピング" },
    { name: "ブロックチェーン" },
    { name: "機械学習" },
    { name: "正規表現" },
  ]
end
